---
version: "2.1"
services:
  webtop:
    image: lscr.io/linuxserver/webtop:latest
    container_name: webtop
    #security_opt:
      #- seccomp:unconfined #optional
    environment:
      - PUID=1000 # id <usuario>
      - PGID=1000
      - TZ=America/Santiago
      #- SUBFOLDER=/ #optional
      - TITLE="Probando Webtop" #optional
    volumes:
      - ./config:/config:Z
      #- /var/run/docker.sock:/var/run/docker.sock #optional
    ports:
      - 3000:3000
      - 3001:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb" #optional
    restart: unless-stopped
